# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=9.2
  - PG_SUPPORTED_VERSIONS=9.3
  - PG_SUPPORTED_VERSIONS=9.4
  - PG_SUPPORTED_VERSIONS=9.5
  - PG_SUPPORTED_VERSIONS=9.6
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12

language: C
dist: trusty
sudo: required

before_install:
  # apt.postgresql.org is already configured, we just need to add devel
  - |
    DIST=trusty-pgdg
    case $PG_SUPPORTED_VERSIONS in
      11|12)
      # update pgdg-source.list
      sudo sed -i -e "s/pgdg.*/pgdg-testing main $PG_SUPPORTED_VERSIONS/" /etc/apt/sources.list.d/pgdg*.list
      DIST=trusty-pgdg-testing
      ;;
    esac
  - sudo apt-get -qq update

install:
  - export DEBIAN_FRONTEND=noninteractive # suppress warnings about deprecated PostgreSQL versions
  # trusty's pg-srv-dev-all is too old, use -t $DIST to force installation of the pgdg version
  - sudo apt-get install -t $DIST debhelper fakeroot postgresql-common postgresql-server-dev-all postgresql-server-dev-$PG_SUPPORTED_VERSIONS
  # install PostgreSQL $PG_SUPPORTED_VERSIONS if not there yet
  - |
    if [ ! -x /usr/lib/postgresql/$PG_SUPPORTED_VERSIONS/bin/postgres ]; then
      sudo /etc/init.d/postgresql stop # stop postgresql again before installing the server
      sudo apt-get install postgresql-$PG_SUPPORTED_VERSIONS
    fi
  # stop the travis-provided cluster
  - sudo /etc/init.d/postgresql stop
  - pg_lsclusters
  - dpkg -l postgresql\* | cat

script:
  - pg_buildext updatecontrol
  - dpkg-buildpackage -us -uc -rfakeroot
  - for deb in ../*.deb; do echo "$deb:"; dpkg-deb --info $deb; dpkg-deb --contents $deb; done
  - sudo dpkg -i ../*.deb
  - pg_buildext -i '--locale=C.UTF-8' -o local_preload_libraries=pgextwlist -o extwlist.extensions=citext,earthdistance,pg_trgm installcheck
